doc(readme): announce InstantSearch compatibility
algolia/react-recommendations pull request #184
Opened 2024-05-16 07:17 UTC by Haroenv

From now on, you can use Algolia Recommend through InstantSearch, simplifying your integration between the two libraries!

Learn how to migrate following the [upgrade guide](https://www.algolia.com/doc/guides/algolia-recommend/upgrade-guides) provided.

```js
instantsearch({
  // No need for a recommendClient anymore
  searchClient,
  indexName,
}).addWidgets([
  frequentlyBoughtTogether({
    container: '#frequentlyBoughtTogether',
    objectIDs: [currentObjectID],
  }),
  relatedProducts({
    container: '#relatedProducts',
    objectIDs: [currentObjectID],
  }),
])
```

```jsx
<InstantSearch searchClient={searchClient} indexName={indexName}>
  <FrequentlyBoughtTogether objectIDs={[currentObjectID]} />
  <RelatedProducts objectIDs={[currentObjectID]} />
</InstantSearch>
```

FX-2846

2024-05-16 07:17 UTC, Haroenv commented on README.md
> +> Learn how to migrate following the [upgrade guide](https://www.algolia.com/doc/guides/algolia-recommend/upgrade-guides) provided.
to check that this link is correct once it's available

2024-05-17 10:15 UTC, sarahdayan requested changes

2024-05-17 10:15 UTC, sarahdayan commented on README.md
> +> Learn how to migrate following the [upgrade guide](https://www.algolia.com/doc/guides/algolia-recommend/upgrade-guides) provided.
```suggestion
> Learn how to migrate following the [upgrade guide](https://www.algolia.com/doc/guides/algolia-recommend/upgrade-guide).
```

2024-05-17 10:15 UTC, sarahdayan commented on README.md
> +> 🙌 From now on you can use Algolia Recommend from withing InstantSearch, simplifying your integration between the two libraries!
```suggestion
> 🙌 From now on you can use Algolia Recommend from InstantSearch, simplifying your integration between the two libraries!
```

2024-05-17 10:15 UTC, sarahdayan commented on README.md
> +instantsearch({
Add imports?

2024-05-17 10:15 UTC, sarahdayan commented on README.md
> +<InstantSearch searchClient={searchClient} indexName={indexName}>
Add imports and wrap into a function?

2024-05-17 12:49 UTC, dhayab requested changes

2024-05-17 12:49 UTC, dhayab commented on README.md
> +} from 'instantsearch.js';
Widgets are imported from `instantsearch.js/es/widgets` I believe.
```suggestion
import instantsearch from 'instantsearch.js';
import {
  frequentlyBoughtTogether,
  relatedProducts,
} from 'instantsearch.js/es/widgets';

```

2024-05-17 13:01 UTC, dhayab approved these changes

2024-05-21 09:05 UTC, sarahdayan commented on README.md
> +> Learn how to migrate following the [upgrade guide](https://www.algolia.com/doc/guides/algolia-recommend/upgrade-guide).
Upgrade guides are the following:
- `/doc/guides/algolia-recommend/upgrade/recommend-js/`
- `/doc/guides/algolia-recommend/upgrade/recommend-react/`

2024-05-21 09:38 UTC, sarahdayan approved these changes

2024-05-21 11:23 UTC, merged